// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzvibdpwsudvvissxxhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6dmliZHB3c3VkdnZpc3N4eGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NTM2MTcsImV4cCI6MjA1ODQyOTYxN30.hY1RukTPyWlvWq_OG68tLkD7E2j4bNgCPljEBDLbmaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);